name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.11"
        - "3.10"
        - "3.9"
        - "pypy3.9"
        - "3.8"
        include:
          - coverage: true
            coverageArgument: --cov-report xml
          - python-version: "pypy3.9"
            coverage: false
            coverageArgument: --no-cov

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: 'setup.cfg'

    - run: python -m pip install --upgrade pip build

    - run: python -m build

    - run: pip install -e '.[dev]'

    - run: pytest ${{ matrix.coverageArgument }}

    - run: pre-commit run --all-files

    - uses: codecov/codecov-action@v3
      if: ${{ matrix.coverage }}
      with:
        flags: python-${{ matrix.python-version }}
        fail_ci_if_error: true
        verbose: true
